import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { roll } from '../src/utils/diceSimulator';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  roll('2d20+1');
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
